### ISSUE TITLE
Refused To Execute Script. MIME type error

### ISSUE THREAD

**Issue by Shivank12batra** [probberechts/d3-soccer#4]
I tried to run this piece of code https://github.com/probberechts/d3-soccer/blob/master/example/pitch.html but including this script tag: <script type="text/javascript" src="./dist/d3-soccer.js"></script> is giving me the following error: 

Refused to execute script from 'http://127.0.0.1:5500/dist/d3-soccer.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by probberechts** [comment]
The <script> element is trying to load some JavaScript. The error message tells you that the URL you have given it points to a HTML file and not a JavaScript program. The server is correctly reporting that it is HTML so the browser is aborting with that error message instead of trying to execute the HTML as JavaScript (which would throw an error).

How did you generate the dist/d3-soccer.js file?

**Comment by Shivank12batra** [comment]
I took an example from pitch.html in the example folder: https://github.com/probberechts/d3-soccer/blob/master/example/pitch.html and simply ran the following code:
![Screenshot (1843)](https://user-images.githubusercontent.com/84995784/229232945-18ed8c10-8a69-452e-b7f0-99fc05da0142.png)

**Comment by probberechts** [comment]
You have to put the `./dist/d3-soccer.js` file there. You can download it [from the github release](https://github.com/probberechts/d3-soccer/releases/download/v0.1.0/d3-soccer.zip) or [install via NPM](https://www.npmjs.com/package/d3-soccer).

**Comment by Shivank12batra** [comment]
tried NPM install earlier and it wasnt working, now works when I download the file from github release. Thanks!
